---
- name: Simple Ansible Playbook for ACITEC2540
  hosts: 10.48.168.221
  gather_facts: no
  connection: local
  vars:
    aci_creds: &aci_login
      hostname: '{{inventory_hostname}}'
      use_proxy: no
      use_ssl: yes
      username: ansible
      password: cisco
      validate_certs: no
  
  tasks:
    - name: add an App Profile to the tenant
      aci_ap:
        <<: *aci_login
        tenant: 'myTenant'
        ap: 'myApp'
      delegate_to: localhost
    - name: add EPGs to App Profile
      aci_epg:
        <<: *aci_login
        tenant: 'myTenant'
        ap: 'myApp'
        epg: 'EPG_One'
        bd: 'myBD'
      delegate_to: localhost
