---
- name: Simple Ansible Playbook for ACITEC2540
  hosts: 10.48.168.221
  gather_facts: no
  connection: local
  vars:
    aci_creds: &aci_login
      hostname: '{{inventory_hostname}}'
      use_proxy: no
      use_ssl: yes
      username: ansible
      password: cisco
      validate_certs: no
  
  tasks:
  - name: create BD attached to our VRF
    aci_bd:
      <<: *aci_login
      tenant: 'myTenant'
      vrf: 'myVRF'
      bd: 'myBD'
    delegate_to: localhost
